username = input("Введите имя: ")
title = input("Введите тему работы: ")
content = input("Введите вид работы: ")
status = input("Определите статус заметки: ")
created_date = input("Введите дату начала выполнения работы в формате дд.мм.гг: ")
issue_date = input("Введите дату окончания выполнения работы в формате дд.мм.гг: ")
print("Имя пользователя: ",username)
print("Тема работы: ",title)
print("Вид работы: ",content)
print("Статус работы: ",status)
print("Дата начала работы: ",created_date)
print("Дата окончания работы: ",issue_date)
