username = input("Введите имя: ")
title = input("Введите тему работы: ")
content = input("Введите вид работы: ")
status = input("Определите статус заметки: ")
created_date = input("Введите дату начала выполнения работы в формате дд.мм.гг: ")
issue_date = input("Введите дату окончания выполнения работы в формате дд.мм.гг: ")
temp_created_date = str(created_date[0:5])
temp_issue_data = str(issue_dat[0:5])
print("Имя пользователя: ",username)
print("Тема работы: ",title)
print("Вид работы: ",content)
print("Статус работы: ",status)
print("Дата начала работы: ", temp_created_date)
print("Дата окончания рабаты:", temp_issue_data)
